### PR TITLE
Press right to submit

### PR DESCRIPTION
**Pull request by firekesti**
@backer ptal

### CODE REVIEW

**Comment by firekesti** [comment]
I have to merge this first, then make the AAR, post it as a release here, then substitute it in the Android TV project. Shouldn't need any code changes in that project though.

**Comment by backer** [comment]
did you create this branch off of dev or master? I don't think it should be merged straight into master haha

**Comment by backer** [comment]
disregard, lol didn't realize this was a different repo at first

**Comment by backer** [comment]
Not well versed in AS stuff but otherwise looks good to me! ➡️ 👉

**Pull request merged**
